### ISSUE TITLE
Should make use of generic classes

### ISSUE THREAD

**Issue by ValiDraganescu** [thetinygoat/typed-ds#1]
Hi, You should make use of generic classes,
instead of 

```
class LLNode {
    data: any
    next: LLNode
    constructor(data: any) {
        this.data = data
        this.next = null
    }
}
```

you should do
```
class LLNode<T> {
    data: T
    next: LLNode<T>
    constructor(data: T) {
        this.data = data
        this.next = null
    }
}
```

that way, who ever uses the `data` property of the node will get type checking

**Comment by thetinygoat** [comment]
Hi, thanks a lot for pointing out. I've gone and implemented generics in the base classes :)
